languageCode = "fr-fr"
title = "template.beta.gouv.fr"
theme = "template.beta.gouv.fr"
relativeURLs = true
sectionPagesMenu = "main"

[markup.goldmark.renderer]
unsafe = true

pluralizelisttitles = false

[markup]
  [markup.highlight]
    lineNos = true
